Resources:
  SomeRuleHandlerServiceRoleBED9DFCD:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: IotRuleStack/SomeRuleHandler/ServiceRole/Resource
  SomeRuleHandler0ED4D493:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters890a6bdb08d56d1ed4b4a6d0c19519ba56af65a51617edf2ce67062836f7d8a0S3BucketE047675B
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters890a6bdb08d56d1ed4b4a6d0c19519ba56af65a51617edf2ce67062836f7d8a0S3VersionKey79164BF1
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters890a6bdb08d56d1ed4b4a6d0c19519ba56af65a51617edf2ce67062836f7d8a0S3VersionKey79164BF1
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - SomeRuleHandlerServiceRoleBED9DFCD
          - Arn
      Runtime: nodejs12.x
    DependsOn:
      - SomeRuleHandlerServiceRoleBED9DFCD
    Metadata:
      aws:cdk:path: IotRuleStack/SomeRuleHandler/Resource
      aws:asset:path: /Users/darrenh/code/ts/cdk-constructs/iot-rule/dist/index.zip
      aws:asset:property: Code
  SomeRule:
    Type: AWS::IoT::TopicRule
    Properties:
      TopicRulePayload:
        Actions:
          - Lambda:
              FunctionArn:
                Fn::GetAtt:
                  - SomeRuleHandler0ED4D493
                  - Arn
        RuleDisabled: false
        Sql: select * from topic
      RuleName: some-rule
    Metadata:
      aws:cdk:path: IotRuleStack/SomeRule
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.22.0,@aws-cdk/assets=1.22.0,@aws-cdk/aws-cloudwatch=1.22.0,@aws-cdk/aws-ec2=1.22.0,@aws-cdk/aws-events=1.22.0,@aws-cdk/aws-iam=1.22.0,@aws-cdk/aws-iot=1.22.0,@aws-cdk/aws-kms=1.22.0,@aws-cdk/aws-lambda=1.22.0,@aws-cdk/aws-logs=1.22.0,@aws-cdk/aws-s3=1.22.0,@aws-cdk/aws-s3-assets=1.22.0,@aws-cdk/aws-sqs=1.22.0,@aws-cdk/aws-ssm=1.22.0,@aws-cdk/core=1.22.0,@aws-cdk/cx-api=1.22.0,@aws-cdk/region-info=1.22.0,jsii-runtime=node.js/v10.16.3
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters890a6bdb08d56d1ed4b4a6d0c19519ba56af65a51617edf2ce67062836f7d8a0S3BucketE047675B:
    Type: String
    Description: S3 bucket for asset "890a6bdb08d56d1ed4b4a6d0c19519ba56af65a51617edf2ce67062836f7d8a0"
  AssetParameters890a6bdb08d56d1ed4b4a6d0c19519ba56af65a51617edf2ce67062836f7d8a0S3VersionKey79164BF1:
    Type: String
    Description: S3 key for asset version "890a6bdb08d56d1ed4b4a6d0c19519ba56af65a51617edf2ce67062836f7d8a0"
  AssetParameters890a6bdb08d56d1ed4b4a6d0c19519ba56af65a51617edf2ce67062836f7d8a0ArtifactHash4248138F:
    Type: String
    Description: Artifact hash for asset "890a6bdb08d56d1ed4b4a6d0c19519ba56af65a51617edf2ce67062836f7d8a0"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

